# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VE7WjOM2Go_6iG0XT5dzgc1T17FPEaI_
"""



import numpy
age = [99,86,87,88,111,86,103,87,94,78,77,85,86]
x = numpy.median(age)
print(x)



agesAry=[]
for i in range(n):
count=0
for j in range(n):
# count the number ages , which is higher than other ages
if(ages[i]>(ages[j])):
count=count+1
# if total number of ages are more than 90% of other ages
# add this age in list
if count>.9*n:

agesAry=[]
for i in range(n):
count=0
for j in range(n):
# count the number ages , which is higher than other ages
if(ages[i]>(ages[j])):
count=count+1
# if total number of ages are more than 90% of other ages
# add this age in list
if count>.9*n:
agesAry.append(ages[i])
print("Age more than 90% of other ages")
for k in range(len(agesAry)):
print(str(agesAry[k]))